### ISSUE TITLE
notes about downtime vs. consistent backup considerations

### ISSUE THREAD

**Issue by wolfoo2931** [pivotal-cf/docs-service-backup#2]
Hello Pivotal Team,

After reading the documentation, I see a few open questions:

- Do I have to ensure that processes don't write data to the backup directory while the backup is executed? This is because I'm concerned that the file based backup might be corrupted when it is executed while there are processes writing to the backup directory?
- If I have a high available service cluster, is it possible to execute the backup only on one node of the cluster. And If it's possible, is it also possible to choose a node which is currently not a master (if the service is based on a master/slave clustering)?

Best Regards,
Oliver

**Comment by scribblingfox** [comment]
Hey @avade, do you have any insight into this request? Can you give some guidelines around these questions?

Thanks!

**Comment by avade** [comment]
Hi @wolfoo2931 - apologies for missing this question.

> Do I have to ensure that processes don't write data to the backup directory while the backup is executed? This is because I'm concerned that the file based backup might be corrupted when it is executed while there are processes writing to the backup directory?

If you have a `source_executable` configured, service-backup will wait for this to complete before uploading the `source_folder`. If you continue to write in the `source_folder` then this may result in unexpected files being uploaded. Our recommendation is to use a folder that is separate to your services data folder. You can then specify a `cleanup_executable` to run after the upload to clear out the folder.

> If I have a high available service cluster, is it possible to execute the backup only on one node of the cluster. And If it's possible, is it also possible to choose a node which is currently not a master (if the service is based on a master/slave clustering)?

It depends on how your BOSH jobs are constructed. For example if `master` and `worker` are distinct jobs, then you can only deploy the `service-backup` on the same instance group as `master`. If `master` is an internal state of the `data-service` job, one pattern is to deploy service-backup in a separate instance group and remotely execute backup commands against the master node.

Another pattern is to deploy `service-backup` on the same instance group and have the `source_executeable` decide if the given node needs to be backed up. This is more complex as it goes against the BOSH model.

Hope this helps.

Alex

**Comment by wolfoo2931** [comment]
Hello Alex,

Thank you for the explanation, this helps. 

Best Regards,
Oliver
